name: Python CI

on:
  push:
    branches: [ master, ci-test*]
    paths-ignore:
      - 'tests/Auto-GPT-test-cassettes'
      - 'tests/integration/challenges/current_score.json'
  pull_request_target:
    branches: [ master, stable , ci-test*]

concurrency:
  group: ${{ format('ci-{0}', github.head_ref && format('pr-{0}', github.event.pull_request.number) || github.sha) }}
  cancel-in-progress: ${{ github.event_name == 'pull_request_target' }}

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      min-python-version: "3.10"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Set up Python ${{ env.min-python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.min-python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: flake8

      - name: Check black formatting
        run: black . --check
        if: success() || failure()

      - name: Check isort formatting
        run: isort . --check
        if: success() || failure()

      - name: Check mypy formatting
        run: mypy
        if: success() || failure()

      - name: Check for unused imports and pass statements
        run: |
          cmd="autoflake --remove-all-unused-imports --recursive --ignore-init-module-imports autogpt tests"
          $cmd --check || (echo "You have unused imports or pass statements, please run '${cmd} --in-place'" && exit 1)

  test:
    permissions:
      # Gives the action the necessary permissions for publishing new
      # comments in pull requests.
      pull-requests: write
      # Gives the action the necessary permissions for pushing data to the
      # python-coverage-comment-action branch, and for editing existing
      # comments (to avoid publishing multiple comments in the same PR)
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          submodules: true
          token: ${{ secrets.PAT_REVIEW }}

      - name: Create Pull Request
        run: |
          current_date_time=$(date +'%Y%m%d%H%M%S')
          new_branch="update-score-${{ github.event.pull_request.number }}-$current_date_time"
          
          git config --global user.name "Auto-GPT-Bot"
          git config --global user.email "github-bot@agpt.co"
          echo "test" >> tests/integration/challenges/current_score.json
          if ! git diff --quiet -- tests/integration/challenges/current_score.json; then
            git add tests/integration/challenges/current_score.json
            git commit -m "Update score"
            git checkout -b $new_branch
          
            echo ${{ secrets.PAT_REVIEW }} | gh auth login --with-token
          
            git remote add base https://github.com/${{ github.event.pull_request.base.repo.full_name }}.git
          
            git push base $new_branch
            echo "Base branch: ${{ github.event.pull_request.head.ref }}"

            gh pr create --title "Update Score In Pull Request Number ${{ github.event.pull_request.number }}" \
            --head "${{ github.actor }}:$new_branch" \
            --base "${{ github.event.pull_request.head.ref }}" \
            --body "This pull request updates the current score of Auto-GPT. Please check the files changed and merge the pull request." \
            --repo ${{ github.event.pull_request.base.repo.full_name }}
          else
            echo "The current score didn't change."
          fi
